In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

You’re going to the mall with your friends and you have 200 dollars to spend from your recent birthday money. You discover a store that has all jeans for 25 dollars and all dresses for 50 dollars. You really, really want to take home 6 items of clothing because you “need” that many new things. Wouldn’t it be clever to find out how many pairs of jeans and how many dresses you can buy so you use the whole 200 dollars (tax not included – your parents promised to pay the tax)?



$$  \left\{ \begin{array}\\ j + d = 6\\ 25j + 50d = 200\\
\end{array} \right. $$

In [ ]:
X = np.array([
    [1, 1],
    [25, 50],

  
])
Y = np.array([
    [6],
    [200]
  
  
])
print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[ 1  1]
 [25 50]]
(2, 2)
[[  6]
 [200]]
(2, 1)


In [ ]:
X_inv = np.linalg.inv(X)
X_inv


array([[ 2.  , -0.04],
       [-1.  ,  0.04]])

In [ ]:
r = X_inv @ Y
r

array([[4.],
       [2.]])

In [ ]:
Y_1 = X @ r
np.array_equal(Y_1, Y)

True

In [ ]:
X_sol = np.linalg.solve(X, Y)
X_sol

array([[4.],
       [2.]])